title: Rustek
email: keithrussell@rustek.me
description: >-
  Journey of an Information Security Professional — sharing insights on
  professional growth, learning, and goal realization in InfoSec.
baseurl: ""
url: "https://rustek.me"
author: Keith Russell

twitter_username: keith_bug_hunt
linkedin_username: keithruss-infosec

theme: minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: twitter, user_url: "https://x.com/keith_bug_hunt" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/keithruss-infosec/" }

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:title/
