remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

title: Rustek
logo: /assets/images/logo.png
name: &name "Keith Russell"
description: "Journey of an Information Security Professional"
url: "https://rustek.me"
baseurl: ""
repository: "snowbird429/snowbird429.github.io"

author:
  name: "Keith Russell"
  avatar: /assets/images/logo.png
  bio: "Information security professional sharing insights on professional growth, learning, and goal realization in InfoSec."
  location: "United States"
  email: "keithrussell@rustek.me"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/keith_bug_hunt"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/keithruss-infosec/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
